# Generated by Django 5.1.7 on 2025-03-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('enfermeiros', '0002_remove_enfermeiro_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeiro',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
        ),
    ]
