# Generated by Django 5.1.7 on 2025-04-04 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doencas', '0002_rename_descrição_doencas_descricao'),
        ('enderecos', '0001_initial'),
        ('enfermeiros', '0003_enfermeiro_endereco'),
        ('medicos', '0001_initial'),
        ('pacientes', '0003_paciente_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doencas.doencas')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco')),
                ('enfermeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfermeiros.enfermeiro')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
