# Generated by Django 5.1.7 on 2025-04-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultas',
            table='consultas',
        ),
    ]
