# Generated by Django 5.1.7 on 2025-03-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermeiro',
            name='endereco',
        ),
    ]
